# Generated by Django 3.2.7 on 2021-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
