# Generated by Django 3.2.7 on 2021-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
