# Generated by Django 3.2.7 on 2021-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
